config/routes.rb
Rails.application.routes.draw do
  get 'top:count', to: 'top#index'
  get '/', to: 'comments#new'
  post '/', to: 'comments#create'

  resources :users

  root to: 'comments#new', as: 'comments'
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :content, presence: true
  validates :user, presence: true

  has_one :user
  accepts_nested_attributes_for :user
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true
  validates :name, uniqueness: true

  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  #def index
  #
  #end

  # GET /comments/1
  # GET /comments/1.json
  #def show
  #  #@user = User.find(@comment.user_id)
  #end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  #def edit
  #end

  # POST /comments
  # POST /comments.json
  def create
    if params.has_key?(:user_name)
      user = User.find_by(name: params[:user_name])
      if user == nil
        user = User.new(name: params[:user_name])
        user.save
      end
    else
      user = User.find(params[:comment][:user_attributes][:id])
    end

    @comment = user.comments.build(content: params[:comment][:content])

    respond_to do |format|
      if user.save
        format.html { redirect_to  user, notice: 'Comment added' }
        format.js   {}
        format.json { render action 'show', status: created, location: comment }
      else
        format.html { render action: 'new' }
        format.json { render json: comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user, :content)
    end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  def index
    @comment = Comment.new
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    count = params.has_key?(:count) ? params[:count] : 10

    @users = User.joins(:comments).group("users.id").order('COUNT(comments.id) DESC').limit(count)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    if params[:order] != nil && params[:order] == 'top10'
      @users = User.order(comments.count)
    else
      @users = User.all
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @comment = @user.comments.build()
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div><p style="font-weight: bold">At <%= comment.created_at %>:</p>
<p><%= comment.content %></p>
<hr />
</div>

app/views/comments/_form.html.erb
<%= form_for @comment do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= label_tag :user_name, "User name:" %><br>
    <%= text_field_tag :user_name, params[:user_name], :placeholder => 'user name' %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content, :placeholder => 'comment\'s content'%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/create.js.erb
$('div#comments').prepend("<%= escape_javascript render(@comment) %>");
$('div#comments').children().first().css({'background-color':'#ffff88'}).animate({'background-color':'#ffffff'}, 1000);
$('#comment_content').val("");
$('#comment_content').focus();

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td></td>
        <td><%= comment.content %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>Add Comment</h1>

<%= render 'form' %>

<%#= link_to 'Back', :back %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>

</p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RjTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav>
  <ul>
    <li><%= link_to "Add comment", "/" %></li>
    <li><%= link_to "Top 10 active users", "/top10" %></li>
  </ul>
</nav>

<div class="content">
  <%= yield %>
</div>

</body>
</html>

app/views/post/index.html.erb
<h1>Add comment</h1>
<%= form_for @comment, :action => 'create' do |f| %>
    <fieldset>
      <div>
        <%= label_tag :user_name, 'User name:' %>
        <%= text_field_tag :user_name, params[:user_name] %>
      </div>

      <div>
        <%= f.label :content, 'Comment:' %>
        <%= f.text_area :content %>
      </div>

      <div>
        <%= f.submit "Send" %>
      </div>
    </fieldset>
<% end %>

app/views/top/index.html.erb
<h1>Top of active users</h1>
<ol>
  <% @users.each do |user| %>
  <li>
    <a href="<%= user_path(id: user.id) %>"><%= user.name %></a> with <%= user.comments.count %> comments.
  </li>
  <% end %>
</ol>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.comments.count %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @user.name %>'s page.
</h1>

<%= form_for @comment, remote: true, :action => 'create' do |f| %>
    <div>
      <%= f.label 'New comment:' %>
      <%= f.text_area :content, :placeholder => 'Comment' %>
    </div>

    <div>
      <%= f.fields_for :user do |ff| %>
        <%= f.hidden_field :id %>
      <% end %>
      <%= f.submit 'Send' %>
    </div>
<% end %>

<p>
<h3><%= @user.name %>'s comments:</h3>
<div id="comments">
  <%= render @user.comments.reverse_order %>
</div>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>